import numpy as np
import matplotlib.pyplot as plt

datos = np.loadtxt("euler_01.dat")
datos2 = np.loadtxt("rompeku_01.dat")
plt.figure(figsize=(15,5))
plt.title("$dx=0.1$")
plt.subplot(1,3,1)
plt.plot(datos[:,0],datos[:,1],label="Explicito")
plt.plot(datos2[:,0],datos2[:,1],label="Runge_Kutta",c='r')
plt.xlabel("$x$")
plt.ylabel("$y$")
plt.legend()
plt.subplot(1,3,2)
plt.plot(datos[:,0],datos[:,2],label="Explicito")
plt.plot(datos2[:,0],datos2[:,2],label="Runge_Kutta",c='r')
plt.xlabel("$x$")
plt.ylabel("$y'$")
plt.legend()
plt.subplot(1,3,3)
plt.plot(datos[:,1],datos[:,2],label="Explicito")
plt.plot(datos2[:,1],datos2[:,2],label="Runge_Kutta",c='r')
plt.xlabel("$y$")
plt.ylabel("$y'$")
plt.legend()
plt.savefig("solucion_01.png")

datos = np.loadtxt("euler_001.dat")
datos2 = np.loadtxt("rompeku_001.dat")
plt.figure(figsize=(15,5))
plt.title("$dx=0.01$")
plt.subplot(1,3,1)
plt.plot(datos[:,0],datos[:,1],label="Explicito")
plt.plot(datos2[:,0],datos2[:,1],label="Runge_Kutta",c='r')
plt.xlabel("$x$")
plt.ylabel("$y$")
plt.legend()
plt.subplot(1,3,2)
plt.plot(datos[:,0],datos[:,2],label="Explicito")
plt.plot(datos2[:,0],datos2[:,2],label="Runge_Kutta",c='r')
plt.xlabel("$x$")
plt.ylabel("$y'$")
plt.legend()
plt.subplot(1,3,3)
plt.plot(datos[:,1],datos[:,2],label="Explicito")
plt.plot(datos2[:,1],datos2[:,2],label="Runge_Kutta",c='r')
plt.xlabel("$y$")
plt.ylabel("$y'$")
plt.legend()
plt.savefig("solucion_001.png")

datos = np.loadtxt("euler_0001.dat")
datos2 = np.loadtxt("rompeku_0001.dat")
plt.figure(figsize=(15,5))
plt.title("$dx=0.001$")
plt.subplot(1,3,1)
plt.plot(datos[:,0],datos[:,1],label="Explicito")
plt.plot(datos2[:,0],datos2[:,1],label="Runge_Kutta",c='r')
plt.xlabel("$x$")
plt.ylabel("$y$")
plt.legend()
plt.subplot(1,3,2)
plt.plot(datos[:,0],datos[:,2],label="Explicito")
plt.plot(datos2[:,0],datos2[:,2],label="Runge_Kutta",c='r')
plt.xlabel("$x$")
plt.ylabel("$y'$")
plt.legend()
plt.subplot(1,3,3)
plt.plot(datos[:,1],datos[:,2],label="Explicito")
plt.plot(datos2[:,1],datos2[:,2],label="Runge_Kutta",c='r')
plt.xlabel("$y$")
plt.ylabel("$y'$")
plt.legend()
plt.savefig("solucion_0001.png")

